// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "AeroFresco",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "AeroFresco",
            targets: ["AppModule"],
            bundleIdentifier: "Alpha123.AeroSketch",
            teamIdentifier: "R2WDS6ZMQ6",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight
            ],
            capabilities: [
                .camera(purposeString: "We need camera to detect your hand movement and show live view")
            ],
            appCategory: .games
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
